# Generated by Django 4.1.4 on 2022-12-31 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_address', models.CharField(max_length=200)),
                ('vendor_contact', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_description',
        ),
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='item',
            name='item_quantity',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='vendor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.vendor'),
        ),
    ]
